server:
    port: 81
    session.timeout: -1


#accounturi: mongodb://test.hwlantian.com:27017
#accountdatabase : account
accounturi: mongodb://root:Hwlantian2123@blueskysensor.com:3718
accountdatabase : account
useruri : mongodb://test.hwlantian.com:27017
userdatabase : sky_user

deviceuri: mongodb://root:Hwlantian2123@blueskysensor.com:3718
devicedatabase : device
spring.redis:
  host: test.hwlantian.com
  port: 6379
  password: Sky.Redis.2014